# Generated by Django 4.2.15 on 2024-12-23 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0001_initial'),
    ]

    operations = [
    ]
