# Generated by Django 4.2.15 on 2024-10-29 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0002_remove_cliente_cpf_cliente_cpf_cnpj'),
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('valor_custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True)),
                ('cliente_nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='Nome do Cliente')),
                ('produtos_utilizados', models.ManyToManyField(to='produto.produto', verbose_name='Produtos Utilizados')),
            ],
        ),
    ]
