# Generated by Django 4.2.15 on 2025-02-13 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('veiculo', '0001_initial'),
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_inicio', models.ImageField(blank=True, upload_to='images/', verbose_name='Foto do veiculo antes da OS')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Data de inicio')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data de entrega')),
                ('foto_fim', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Foto do veiculo depois da OS')),
                ('mao_obra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da mão de obra')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.TextField(blank=True, verbose_name='OBSERVAÇÕES')),
                ('cliente_nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='Nome do Cliente')),
                ('veiculo', models.ManyToManyField(to='veiculo.veiculo', verbose_name='Veiculo do Cliente')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
            },
        ),
        migrations.CreateModel(
            name='OSProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='os_produtos', to='ordem_servico.os')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto_os', to='produto.produto')),
            ],
        ),
    ]
