# Generated by Django 4.2.15 on 2024-11-09 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0001_initial'),
        ('cliente', '0002_remove_cliente_cpf_cliente_cpf_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_inicio', models.ImageField(blank=True, upload_to='images/', verbose_name='Foto do veiculo antes da OS')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Data de inicio')),
                ('data_fim', models.DateTimeField(null=True, verbose_name='Data de entrega')),
                ('foto_fim', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Foto do veiculo depois da OS')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('mao_obra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da mão de obra')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.TextField(blank=True, verbose_name='OBSERVAÇÕES')),
                ('cliente_nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='Nome do Cliente')),
                ('produtos_utilizados', models.ManyToManyField(to='produto.produto', verbose_name='Produtos Utilizados')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
            },
        ),
    ]
