# Generated by Django 4.2.15 on 2024-11-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculo', '0001_initial'),
        ('ordem_servico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='os',
            name='veiculo',
            field=models.ManyToManyField(to='veiculo.veiculo', verbose_name='Veiculo do Cliente'),
        ),
    ]
