# Generated by Django 4.2.15 on 2024-12-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_servico', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='os',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de entrega'),
        ),
    ]
