# Generated by Django 4.2.15 on 2025-01-28 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
        ('ordem_servico', '0003_alter_os_data_fim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='os',
            name='produtos_utilizados',
        ),
        migrations.CreateModel(
            name='OSProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='os_produtos', to='ordem_servico.os')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto_os', to='produto.produto')),
            ],
        ),
    ]
