# Generated by Django 4.2.15 on 2025-01-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_servico', '0004_remove_os_produtos_utilizados_osproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='os',
            name='status',
            field=models.BooleanField(default=True, verbose_name='STATUS'),
        ),
    ]
