# Generated by Django 4.2.15 on 2025-02-13 19:33

import cliente.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='NOME')),
                ('cpf_cnpj', models.CharField(max_length=18, validators=[cliente.validators.validate_cpf_cnpj], verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='NASCIDO EM')),
                ('telefone', models.CharField(max_length=20, validators=[cliente.validators.validate_phone], verbose_name='TELEFONE 1')),
                ('telefone2', models.CharField(blank=True, max_length=20, validators=[cliente.validators.validate_phone], verbose_name='TELEFONE 2')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='EMAIL')),
                ('endereco_cep', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('endereco_logradouro', models.CharField(blank=True, max_length=255, verbose_name='ENDEREÇO')),
                ('endereco_numero', models.CharField(blank=True, max_length=10, verbose_name='NÚMERO')),
                ('endereco_bairro', models.CharField(blank=True, max_length=255, verbose_name='BAIRRO')),
                ('endereco_cidade', models.CharField(blank=True, max_length=255, verbose_name='CIDADE')),
                ('endereco_estado', models.CharField(blank=True, choices=[['AC', 'Acre'], ['AL', 'Alagoas'], ['AP', 'Amapá'], ['AM', 'Amazonas'], ['BA', 'Bahia'], ['CE', 'Ceará'], ['ES', 'Espírito Santo'], ['GO', 'Goiás'], ['MA', 'Maranhão'], ['MT', 'Mato Grosso'], ['MS', 'Mato Grosso do Sul'], ['MG', 'Minas Gerais'], ['PA', 'Pará'], ['PB', 'Paraíba'], ['PR', 'Paraná'], ['PE', 'Pernambuco'], ['PI', 'Piauí'], ['RJ', 'Rio de Janeiro'], ['RN', 'Rio Grande do Norte'], ['RS', 'Rio Grande do Sul'], ['RO', 'Rondônia'], ['RR', 'Roraima'], ['SC', 'Santa Catarina'], ['SP', 'São Paulo'], ['SE', 'Sergipe'], ['TO', 'Tocantins'], ['DF', 'Distrito Federal']], max_length=2, verbose_name='ESTADO')),
                ('endereco_complemento', models.CharField(blank=True, max_length=255, verbose_name='COMPLEMENTO')),
                ('observacao', models.TextField(blank=True, verbose_name='OBSERVAÇÕES')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='CRIADO EM')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
