# Generated by Django 4.2.15 on 2024-10-16 03:28

import cliente.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cpf',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.CharField(default=11111111111, max_length=18, validators=[cliente.validators.validate_cpf_cnpj], verbose_name='CPF'),
            preserve_default=False,
        ),
    ]
